name: publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: NuGet/setup-nuget@v1.0.5
    - run: dotnet build --configuration Release
    - name: Push to NuGet
      run: dotnet nuget push Package\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://nuget.org --skip-duplicate
    - name: Add GPR Source
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/victorx64/index.json -Username victorx64 -Password ${{ secrets.GITHUB_TOKEN }}	
    - name: Push to GitHub Packages
      run: nuget push Package\*.nupkg -Source "GPR" -SkipDuplicate
